spring.application.name=Journel-App 
#localhost for local env and it will change according to other environment
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#if authentication is applied on db then we have to use these 
# spring.data.mongodb.username=yourUserName
# spring.data.mongodb.password=yourPassword

#by default mongodb will not do indexing this will allow the mongodb to do indexing
spring.data.mongodb.auto-index-creation=true
